#!/bin/sh
# usage $0 [input] [output]
ext=$(echo $1 | awk -F '.' '{print $NF}')
cap="Usage: ixo-extractor [input] [output.cbr|cbz|kra]"
if [ -z "$1" ]; then echo $cap; exit 0
else
	unzip -qq -c "$1" mergedimage.png > "$2"
fi
